In [1]:
import pandas as pd
from sklearn.neighbors import KNeighborsRegressor

from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_squared_error

In [2]:
DATA_PATH = '../data/'

df = pd.read_csv(DATA_PATH + 'processed/train_folds.csv')
df.head()

,n,p,f,x,y,z,a1,a2,a3,a4,...,g1g20.95,l1l20.05,l1l20.25,l1l20.75,l1l20.95,l3l40.05,l3l40.25,l3l40.75,l3l40.95,kfold
0,709,0.7,0.2,16,12,7,3.8,0.24,2.3,0.28,...,1.008427,-2.320280,-0.864735,1.158735,2.614280,-2.542766,-0.990184,1.168184,2.720766,0.0
1,921,0.6,0.3,19,17,10,3.0,0.12,2.4,0.19,...,2.052824,-2.445766,-0.893184,1.265184,2.817766,-2.884737,-1.138082,1.290082,3.036737,4.0
2,177,0.8,0.4,14,12,5,3.2,0.17,1.8,0.18,...,2.338795,-1.103398,-0.424143,0.520143,1.199398,-0.913912,-0.331694,0.477694,1.059912,3.0
3,415,0.7,0.5,24,11,2,1.3,0.17,1.5,0.18,...,1.872339,-1.164883,-0.388592,0.690592,1.466883,-1.787339,-0.719939,0.763939,1.831339,0.0
4,802,0.8,0.4,21,10,3,4.4,0.15,2.6,0.13,...,3.169222,-3.002222,-1.158531,1.404531,3.248222,-1.763339,-0.695939,0.787939,1.855339,4.0

In [3]:
def treinar_fold(fold, regressor):
    df_train = df[df.kfold != fold].reset_index(drop=True)
    df_valid = df[df.kfold == fold].reset_index(drop=True)
    
    x_train = df_train.drop(['kfold', 'cent_price_cor', 'cent_trans_cor'], axis=1)
    y_train = df_train[['cent_price_cor', 'cent_trans_cor']]
    x_valid = df_valid.drop(['kfold', 'cent_price_cor', 'cent_trans_cor'], axis=1)
    y_valid = df_valid[['cent_price_cor', 'cent_trans_cor']]
    
    regressor.fit(x_train, y_train)
    y_pred = regressor.predict(x_valid)
    
    mse = mean_squared_error(y_valid, y_pred)
    
    df_valid.loc[:, 'knn_pred_price'] = y_pred[:, 0]
    df_valid.loc[:, 'knn_pred_trans'] = y_pred[:, 1]
    
    return df_valid, mse

In [4]:
reg = MultiOutputRegressor(KNeighborsRegressor(n_neighbors=700))

dfs = []
mean_mse = 0;
for i in range(5):
    fold_df, fold_mse = treinar_fold(i, reg)
    mean_mse += fold_mse
    dfs.append(fold_df)
mean_mse /= 5

fin_valid_df = pd.concat(dfs)
print(f'MSE Media:{mean_mse}')
print(fin_valid_df.shape)
fin_valid_df.to_csv('model_preds/knn.csv', index=False)
# Melhor 700 - Fazer media ser um modelo separado (bom preditor)

MSE Media:0.013461585975387566
(11940, 69)

In [5]:
pd.read_csv('model_preds/knn.csv')

,n,p,f,x,y,z,a1,a2,a3,a4,...,l1l20.25,l1l20.75,l1l20.95,l3l40.05,l3l40.25,l3l40.75,l3l40.95,kfold,knn_pred_price,knn_pred_trans
0,709,0.7,0.2,16,12,7,3.8,0.24,2.3,0.28,...,-0.864735,1.158735,2.614280,-2.542766,-0.990184,1.168184,2.720766,0.0,-0.199641,-0.199641
1,415,0.7,0.5,24,11,2,1.3,0.17,1.5,0.18,...,-0.388592,0.690592,1.466883,-1.787339,-0.719939,0.763939,1.831339,0.0,-0.205234,-0.205234
2,231,0.7,0.3,21,12,8,4.7,0.28,2.0,0.23,...,-0.345143,0.599143,1.278398,-1.250883,-0.474592,0.604592,1.380883,0.0,-0.202009,-0.202009
3,286,0.8,0.3,15,14,2,2.8,0.18,3.2,0.14,...,-0.362143,0.582143,1.261398,-2.884737,-1.138082,1.290082,3.036737,0.0,-0.204926,-0.204926
4,788,0.7,0.5,27,12,9,2.0,0.25,2.9,0.14,...,-0.422592,0.656592,1.432883,-2.093310,-0.831837,0.921837,2.183310,0.0,-0.202181,-0.202181
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11935,660,0.9,0.3,24,18,4,4.1,0.20,2.4,0.20,...,-0.543490,0.805490,1.775854,-1.462368,-0.589041,0.625041,1.498368,4.0,-0.205311,-0.205311
11936,592,0.8,0.3,21,18,3,2.0,0.19,1.5,0.22,...,-0.165245,0.509245,0.994427,-3.098222,-1.254531,1.308531,3.152222,4.0,-0.194449,-0.194449
11937,511,0.5,0.5,28,28,3,3.9,0.25,1.6,0.23,...,-0.830286,1.058286,2.416795,-1.632854,-0.662490,0.686490,1.656854,4.0,-0.201590,-0.201590
11938,255,0.6,0.5,20,28,2,4.4,0.28,1.2,0.24,...,-0.662490,0.686490,1.656854,-1.120398,-0.441143,0.503143,1.182398,4.0,-0.202470,-0.202470
11939,629,0.5,0.3,17,10,10,4.3,0.26,1.3,0.16,...,-0.972184,1.186184,2.738766,-2.618766,-1.066184,1.092184,2.644766,4.0,-0.208710,-0.208710

In [6]:
test_df = pd.read_csv(DATA_PATH + 'processed/test_input.csv')
test_df.head()

,n,p,f,x,y,z,a1,a2,a3,a4,...,g1g20.75,g1g20.95,l1l20.05,l1l20.25,l1l20.75,l1l20.95,l3l40.05,l3l40.25,l3l40.75,l3l40.95
0,558,0.5,0.2,28,21,2,1.0,0.29,1.3,0.21,...,1.412082,3.158737,-3.140707,-1.199980,1.497980,3.438707,-2.718251,-1.068633,1.224633,2.874251
1,910,0.9,0.3,28,19,9,2.2,0.14,1.6,0.14,...,0.846490,1.816854,-1.229883,-0.453592,0.625592,1.401883,-1.285883,-0.509592,0.569592,1.345883
2,213,0.8,0.5,21,15,8,2.2,0.22,2.6,0.15,...,0.555143,1.234398,-2.283795,-0.925286,0.963286,2.321795,-1.957824,-0.793388,0.825388,1.989824
3,654,0.7,0.5,14,15,2,2.2,0.12,3.8,0.27,...,1.061837,2.323310,-1.205883,-0.429592,0.649592,1.425883,-2.790251,-1.140633,1.152633,2.802251
4,672,0.7,0.5,24,10,5,3.7,0.20,3.7,0.18,...,0.765041,1.638368,-2.977222,-1.133531,1.429531,3.273222,-2.100310,-0.838837,0.914837,2.176310

In [7]:
X_train = df.drop(['kfold', 'cent_price_cor', 'cent_trans_cor'], axis=1)
y_train = df[['cent_price_cor', 'cent_trans_cor']]

reg.fit(X_train, y_train)

y_pred = reg.predict(test_df.values)

df_submission = pd.DataFrame(y_pred, columns=['cent_price_cor', 'cent_trans_cor'])
df_submission

      cent_price_cor  cent_trans_cor
0          -0.199809        0.368067
1          -0.204037        0.364823
2          -0.201943        0.357534
3          -0.201533        0.366661
4          -0.196560        0.360271
...              ...             ...
8054       -0.204091        0.363123
8055       -0.204170        0.368757
8056       -0.203924        0.361280
8057       -0.202797        0.364626
8058       -0.201246        0.362159

[8059 rows x 2 columns]

In [8]:
df_submission.to_csv('model_preds/knn_sub.csv', index=False)

In [9]:
test_df = pd.read_csv(DATA_PATH + 'processed/test_input.csv')
test_df.head()

,n,p,f,x,y,z,a1,a2,a3,a4,...,g1g20.75,g1g20.95,l1l20.05,l1l20.25,l1l20.75,l1l20.95,l3l40.05,l3l40.25,l3l40.75,l3l40.95
0,558,0.5,0.2,28,21,2,1.0,0.29,1.3,0.21,...,1.412082,3.158737,-3.140707,-1.199980,1.497980,3.438707,-2.718251,-1.068633,1.224633,2.874251
1,910,0.9,0.3,28,19,9,2.2,0.14,1.6,0.14,...,0.846490,1.816854,-1.229883,-0.453592,0.625592,1.401883,-1.285883,-0.509592,0.569592,1.345883
2,213,0.8,0.5,21,15,8,2.2,0.22,2.6,0.15,...,0.555143,1.234398,-2.283795,-0.925286,0.963286,2.321795,-1.957824,-0.793388,0.825388,1.989824
3,654,0.7,0.5,14,15,2,2.2,0.12,3.8,0.27,...,1.061837,2.323310,-1.205883,-0.429592,0.649592,1.425883,-2.790251,-1.140633,1.152633,2.802251
4,672,0.7,0.5,24,10,5,3.7,0.20,3.7,0.18,...,0.765041,1.638368,-2.977222,-1.133531,1.429531,3.273222,-2.100310,-0.838837,0.914837,2.176310

In [10]:
X_train = df.drop(['kfold', 'cent_price_cor', 'cent_trans_cor'], axis=1)
y_train = df[['cent_price_cor', 'cent_trans_cor']]

reg.fit(X_train, y_train)

y_pred = reg.predict(test_df.values)

df_submission = pd.DataFrame(y_pred, columns=['knn_pred_price', 'knn_pred_trans'])
df_submission

      knn_pred_price  knn_pred_trans
0          -0.199809        0.368067
1          -0.204037        0.364823
2          -0.201943        0.357534
3          -0.201533        0.366661
4          -0.196560        0.360271
...              ...             ...
8054       -0.204091        0.363123
8055       -0.204170        0.368757
8056       -0.203924        0.361280
8057       -0.202797        0.364626
8058       -0.201246        0.362159

[8059 rows x 2 columns]

In [11]:
df_submission.to_csv('model_preds/knn_sub.csv', index=False)